class AppConstants {
  static const String lastProject = 'lastProject';
  static const String baseUrl = 'http://localhost:8090';
  // static const String baseUrl = 'https://jsdaddy.io/company-id/api';
  static const String slackUrl =
      'https://app.slack.com/client/T5WCD8R5H/user_profile';
  static const String Statistics = 'Statistics';
  static const String Timelog = 'Timelog';
  static const String Employees = 'Employees';
  static const String Projects = 'Projects';
  static const String Rules = 'Rules';
  static const String Paid = 'Paid';
  static const String NonPaid = 'Non-paid';
  static const String Vacation = 'Vacation';
  static const String Sickness = 'Sickness';
  static const String All = 'All';
  static const String Ongoing = 'Ongoing';
  static const String Finished = 'Finished';
  static const String Rejected = 'Rejected';
  static const String Internal = 'Internal';
  static const String Commercial = 'Commercial';
  static const String Log = 'Log';
  static const String Owner = 'Owner';
  static const String Developer = 'Developer';
  static const String owner = 'owner';
  static const String developer = 'developer';
  static const String approved = 'approved';
  static const String vacations = 'vacations';
  static const String timelogs = 'timelogs';
  static const String finished = 'finished';
  static const String all = 'all';
  static const String ongoing = 'ongoing';
  static const String rejected = 'rejected';
  static const String pending = 'pending';
  static const String VacationPaid = 'VacationPaid';
  static const String VacationNonPaid = 'VacationNonPaid';
  static const String SickPaid = 'SickPaid';
  static const String SickNonPaid = 'SickNonPaid';
}
